project_id = "ybmtjbnrslczpgjdaxry"

[functions.translate]
verify_jwt = false

[functions.send-push]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.webhook-receiver]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.create-webhook]
verify_jwt = true

[functions.regenerate-webhook-secret]
verify_jwt = true

[functions.test-webhook]
verify_jwt = true
